spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

minigames:
  testprop: server_devprofile_prop